apiVersion: v1
kind: Service
metadata:
  name: memcached-service
  namespace: memcached
  labels:
    app: memcached
spec:
  type: ClusterIP
  ports:
  - port: 11211
    targetPort: 11211
  selector:
    app: memcached