apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wyvern-base
  namespace: wyvern
  labels:
    app: wyvern-base
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: wyvern-base
    spec:
      containers:
      - name: wyvern-base-app
        image: vovabcps/wyvern-app:latest
        # delete in production
        imagePullPolicy: Always
        env:
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql
                  key: password
        ports:
        - containerPort: 8080
      volumes:
        - name: cloudsql-oauth-credentials
          secret:
            secretName: cloudsql-oauth-credentials
        - name: cloudsql
          emptyDir: {}
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs